### ISSUE TITLE
Concurrent access with duckdb

### ISSUE THREAD

**Issue by loicalleyne** [dbrest-io/dbREST#4]
Does dbREST queue queries to duckdb or can it run queries concurrently? Does using interactive mode make a difference?

**Comment by flarco** [comment]
The way it is currently, isn't suitable for concurrent duckdb access, because it will try to re-use the same connection.

2 Ideas:
- Create multiple dbREST connections pointing to the same duckdb file. Have your reverse-proxy cycle between them (load balancer). The key is to make sure to specify `read_only` mode (to allow concurrent readers) AND `interactive` mode so that it doesn't reopen the connection each request.
- Another thought is to add a pool functionality inside dbREST to allow this. I'm thinking it's not so much work, would need to specify the number of read-only connections to open and hold them in a map as a pool. Check out https://github.com/dbrest-io/dbREST/blob/main/state/project.go#L240-L280. Feel free to open a PR, I don't have much time to implement this at the moment.
